server:
  port: 8081
#spring:
#  security:
#    user:
#      name: user
#      password: pass
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
