server:
  port: 8085
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/carDB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
